//! Base instruction family for LoongArch.
//!
//! Covers integer ALU, bitwise, privileged, and other non-specialized
//! instructions decoded from the auto-generated Capstone tables.

use robustone_core::ir::{DecodedInstruction, RenderHints};
use robustone_core::types::error::DisasmError;

use crate::decoder_generated;
use crate::extensions::{InstructionFamily, build_decoded_instruction};

/// Base family dispatching to the generated exact-word decoder.
pub struct BaseFamily;

fn is_base(mnemonic: &str) -> bool {
    matches!(
        mnemonic,
        "adc.b"
            | "adc.d"
            | "adc.h"
            | "adc.w"
            | "add.w"
            | "addi.w"
            | "addu12i.d"
            | "addu12i.w"
            | "alsl.w"
            | "and"
            | "andi"
            | "andn"
            | "armadc.w"
            | "armadd.w"
            | "armand.w"
            | "armmfflag"
            | "armmov.d"
            | "armmov.w"
            | "armmove"
            | "armmtflag"
            | "armnot.w"
            | "armor.w"
            | "armrotr.w"
            | "armrotri.w"
            | "armrrx.w"
            | "armsbc.w"
            | "armsll.w"
            | "armslli.w"
            | "armsra.w"
            | "armsrai.w"
            | "armsrl.w"
            | "armsrli.w"
            | "armsub.w"
            | "armxor.w"
            | "bitrev.4b"
            | "bitrev.w"
            | "break"
            | "bstrins.w"
            | "bstrpick.w"
            | "bytepick.w"
            | "cacop"
            | "clo.w"
            | "clz.w"
            | "cpucfg"
            | "crc.w.b.w"
            | "crc.w.d.w"
            | "crc.w.h.w"
            | "crc.w.w.w"
            | "crcc.w.b.w"
            | "crcc.w.d.w"
            | "crcc.w.h.w"
            | "crcc.w.w.w"
            | "csrrd"
            | "csrwr"
            | "csrxchg"
            | "cto.w"
            | "ctz.w"
            | "dbcl"
            | "div.w"
            | "div.wu"
            | "ertn"
            | "fabs.d"
            | "fabs.s"
            | "fadd.d"
            | "fadd.s"
            | "fclass.d"
            | "fclass.s"
            | "fcmp.caf.d"
            | "fcmp.caf.s"
            | "fcmp.ceq.d"
            | "fcmp.ceq.s"
            | "fcmp.cle.d"
            | "fcmp.cle.s"
            | "fcmp.clt.d"
            | "fcmp.clt.s"
            | "fcmp.cne.d"
            | "fcmp.cne.s"
            | "fcmp.cor.d"
            | "fcmp.cor.s"
            | "fcmp.cueq.d"
            | "fcmp.cueq.s"
            | "fcmp.cule.d"
            | "fcmp.cule.s"
            | "fcmp.cult.d"
            | "fcmp.cult.s"
            | "fcmp.cun.d"
            | "fcmp.cun.s"
            | "fcmp.cune.d"
            | "fcmp.cune.s"
            | "fcmp.saf.d"
            | "fcmp.saf.s"
            | "fcmp.seq.d"
            | "fcmp.seq.s"
            | "fcmp.sle.d"
            | "fcmp.sle.s"
            | "fcmp.slt.d"
            | "fcmp.slt.s"
            | "fcmp.sne.d"
            | "fcmp.sne.s"
            | "fcmp.sor.d"
            | "fcmp.sor.s"
            | "fcmp.sueq.d"
            | "fcmp.sueq.s"
            | "fcmp.sule.d"
            | "fcmp.sule.s"
            | "fcmp.sult.d"
            | "fcmp.sult.s"
            | "fcmp.sun.d"
            | "fcmp.sun.s"
            | "fcmp.sune.d"
            | "fcmp.sune.s"
            | "fcopysign.d"
            | "fcopysign.s"
            | "fcvt.d.ld"
            | "fcvt.d.s"
            | "fcvt.ld.d"
            | "fcvt.s.d"
            | "fcvt.ud.d"
            | "fdiv.d"
            | "fdiv.s"
            | "ffint.d.l"
            | "ffint.d.w"
            | "ffint.s.l"
            | "ffint.s.w"
            | "fld.d"
            | "fld.s"
            | "fldgt.d"
            | "fldgt.s"
            | "fldle.d"
            | "fldle.s"
            | "fldx.d"
            | "fldx.s"
            | "flogb.d"
            | "flogb.s"
            | "fmadd.d"
            | "fmadd.s"
            | "fmax.d"
            | "fmax.s"
            | "fmaxa.d"
            | "fmaxa.s"
            | "fmin.d"
            | "fmin.s"
            | "fmina.d"
            | "fmina.s"
            | "fmov.d"
            | "fmov.s"
            | "fmsub.d"
            | "fmsub.s"
            | "fmul.d"
            | "fmul.s"
            | "fneg.d"
            | "fneg.s"
            | "fnmadd.d"
            | "fnmadd.s"
            | "fnmsub.d"
            | "fnmsub.s"
            | "frecip.d"
            | "frecip.s"
            | "frecipe.d"
            | "frecipe.s"
            | "frint.d"
            | "frint.s"
            | "frsqrt.d"
            | "frsqrt.s"
            | "frsqrte.d"
            | "frsqrte.s"
            | "fscaleb.d"
            | "fscaleb.s"
            | "fsel"
            | "fsqrt.d"
            | "fsqrt.s"
            | "fst.d"
            | "fst.s"
            | "fstgt.d"
            | "fstgt.s"
            | "fstle.d"
            | "fstle.s"
            | "fstx.d"
            | "fstx.s"
            | "fsub.d"
            | "fsub.s"
            | "ftint.l.d"
            | "ftint.l.s"
            | "ftint.w.d"
            | "ftint.w.s"
            | "ftintrm.l.d"
            | "ftintrm.l.s"
            | "ftintrm.w.d"
            | "ftintrm.w.s"
            | "ftintrne.l.d"
            | "ftintrne.l.s"
            | "ftintrne.w.d"
            | "ftintrne.w.s"
            | "ftintrp.l.d"
            | "ftintrp.l.s"
            | "ftintrp.w.d"
            | "ftintrp.w.s"
            | "ftintrz.l.d"
            | "ftintrz.l.s"
            | "ftintrz.w.d"
            | "ftintrz.w.s"
            | "gcsrrd"
            | "gcsrwr"
            | "gcsrxchg"
            | "gtlbflush"
            | "hvcl"
            | "idle"
            | "invtlb"
            | "iocsrrd.b"
            | "iocsrrd.h"
            | "iocsrrd.w"
            | "iocsrwr.b"
            | "iocsrwr.h"
            | "iocsrwr.w"
            | "jiscr0"
            | "jiscr1"
            | "lddir"
            | "ldgt.b"
            | "ldgt.d"
            | "ldgt.h"
            | "ldgt.w"
            | "ldl.d"
            | "ldl.w"
            | "ldle.b"
            | "ldle.d"
            | "ldle.h"
            | "ldle.w"
            | "ldpte"
            | "ldr.d"
            | "ldr.w"
            | "lu12i.w"
            | "maskeqz"
            | "masknez"
            | "mod.w"
            | "mod.wu"
            | "movcf2fr"
            | "movcf2gr"
            | "move"
            | "movfcsr2gr"
            | "movfr2cf"
            | "movfr2gr.s"
            | "movgr2cf"
            | "movgr2fcsr"
            | "movgr2fr.w"
            | "movgr2scr"
            | "movscr2gr"
            | "mul.w"
            | "mulh.w"
            | "mulh.wu"
            | "nop"
            | "nor"
            | "or"
            | "ori"
            | "orn"
            | "pcaddi"
            | "pcaddu12i"
            | "pcalau12i"
            | "rcr.b"
            | "rcr.d"
            | "rcr.h"
            | "rcr.w"
            | "rcri.b"
            | "rcri.d"
            | "rcri.h"
            | "rcri.w"
            | "rdtimeh.w"
            | "rdtimel.w"
            | "revb.2h"
            | "rotr.b"
            | "rotr.h"
            | "rotr.w"
            | "rotri.b"
            | "rotri.h"
            | "rotri.w"
            | "sbc.b"
            | "sbc.d"
            | "sbc.h"
            | "sbc.w"
            | "setarmj"
            | "setx86j"
            | "setx86loope"
            | "setx86loopne"
            | "sll.w"
            | "slli.w"
            | "slt"
            | "slti"
            | "sltu"
            | "sltui"
            | "sra.w"
            | "srai.w"
            | "srl.w"
            | "srli.w"
            | "stgt.b"
            | "stgt.d"
            | "stgt.h"
            | "stgt.w"
            | "stl.d"
            | "stl.w"
            | "stle.b"
            | "stle.d"
            | "stle.h"
            | "stle.w"
            | "str.d"
            | "str.w"
            | "sub.w"
            | "syscall"
            | "tlbclr"
            | "tlbfill"
            | "tlbflush"
            | "tlbrd"
            | "tlbsrch"
            | "tlbwr"
            | "x86adc.b"
            | "x86adc.d"
            | "x86adc.h"
            | "x86adc.w"
            | "x86add.b"
            | "x86add.d"
            | "x86add.du"
            | "x86add.h"
            | "x86add.w"
            | "x86add.wu"
            | "x86and.b"
            | "x86and.d"
            | "x86and.h"
            | "x86and.w"
            | "x86clrtm"
            | "x86dec.b"
            | "x86dec.d"
            | "x86dec.h"
            | "x86dec.w"
            | "x86dectop"
            | "x86inc.b"
            | "x86inc.d"
            | "x86inc.h"
            | "x86inc.w"
            | "x86inctop"
            | "x86mfflag"
            | "x86mftop"
            | "x86mtflag"
            | "x86mttop"
            | "x86mul.b"
            | "x86mul.bu"
            | "x86mul.d"
            | "x86mul.du"
            | "x86mul.h"
            | "x86mul.hu"
            | "x86mul.w"
            | "x86mul.wu"
            | "x86or.b"
            | "x86or.d"
            | "x86or.h"
            | "x86or.w"
            | "x86rcl.b"
            | "x86rcl.d"
            | "x86rcl.h"
            | "x86rcl.w"
            | "x86rcli.b"
            | "x86rcli.d"
            | "x86rcli.h"
            | "x86rcli.w"
            | "x86rcr.b"
            | "x86rcr.d"
            | "x86rcr.h"
            | "x86rcr.w"
            | "x86rcri.b"
            | "x86rcri.d"
            | "x86rcri.h"
            | "x86rcri.w"
            | "x86rotl.b"
            | "x86rotl.d"
            | "x86rotl.h"
            | "x86rotl.w"
            | "x86rotli.b"
            | "x86rotli.d"
            | "x86rotli.h"
            | "x86rotli.w"
            | "x86rotr.b"
            | "x86rotr.d"
            | "x86rotr.h"
            | "x86rotr.w"
            | "x86rotri.b"
            | "x86rotri.d"
            | "x86rotri.h"
            | "x86rotri.w"
            | "x86sbc.b"
            | "x86sbc.d"
            | "x86sbc.h"
            | "x86sbc.w"
            | "x86settag"
            | "x86settm"
            | "x86sll.b"
            | "x86sll.d"
            | "x86sll.h"
            | "x86sll.w"
            | "x86slli.b"
            | "x86slli.d"
            | "x86slli.h"
            | "x86slli.w"
            | "x86sra.b"
            | "x86sra.d"
            | "x86sra.h"
            | "x86sra.w"
            | "x86srai.b"
            | "x86srai.d"
            | "x86srai.h"
            | "x86srai.w"
            | "x86srl.b"
            | "x86srl.d"
            | "x86srl.h"
            | "x86srl.w"
            | "x86srli.b"
            | "x86srli.d"
            | "x86srli.h"
            | "x86srli.w"
            | "x86sub.b"
            | "x86sub.d"
            | "x86sub.du"
            | "x86sub.h"
            | "x86sub.w"
            | "x86sub.wu"
            | "x86xor.b"
            | "x86xor.d"
            | "x86xor.h"
            | "x86xor.w"
            | "xor"
            | "xori"
    )
}

impl InstructionFamily for BaseFamily {
    fn try_decode(&self, word: u32, addr: u64) -> Option<Result<DecodedInstruction, DisasmError>> {
        match decoder_generated::decode_loongarch_word(word) {
            Ok((mnemonic, operands, size)) => {
                if !is_base(mnemonic) {
                    return None;
                }

                let mut render_hints = RenderHints::default();
                match mnemonic {
                    "nop" => {
                        render_hints.capstone_hidden_operands = vec![0, 1, 2];
                    }
                    "move" => {
                        render_hints.capstone_hidden_operands = vec![2];
                    }
                    _ => {}
                }

                // Capstone renders invtlb as "invtlb imm, Rj, Rk" but the
                // generated decoder produces operands in wire order "Rk, Rj, imm".
                let operands: Vec<_> = if mnemonic == "invtlb" && operands.len() == 3 {
                    vec![
                        operands[2].clone(),
                        operands[1].clone(),
                        operands[0].clone(),
                    ]
                } else {
                    operands
                };

                let mut decoded = build_decoded_instruction(mnemonic, operands, size, word, addr);
                decoded.render_hints = render_hints;
                Some(Ok(decoded))
            }
            Err(e) => Some(Err(e)),
        }
    }

    fn name(&self) -> &'static str {
        "base"
    }
}
