//! LoongArch backend implementing the `robustone-isa` `ArchitectureBackend` trait.

use robustone_core::ir::{ArchitectureId, RegisterId};
use robustone_core::types::error::DisasmError;
use robustone_isa::{
    Access, AliasPolicy, DecodeProfile, FeatureSet, ImmediateKind, ImmediateTransform,
    InstructionGroup, InstructionRead, InstructionSpec, RenderDialect, RenderPolicy,
};

// ============================================================================
// LoongArch types — generated by define_arch!
// ============================================================================

robustone_isa_macros::define_arch! {
    pub arch LoongArch {
        word = u32;
        endian = little;
        instruction_length = fixed(4);
        modes {
            LA32 = "loongarch32";
            LA64 = "loongarch64";
        };
        features: u16 {
            BASE       = 0;
            LA64       = 1;
            FLOAT32    = 2;
            FLOAT64    = 3;
            PRIVILEGED = 4;
            ATOMIC     = 5;
            LSX        = 6;
            LASX       = 7;
            LVZ        = 8;
            LBT        = 9;
        };
        registers = loongarch_registers;
        formats = loongarch_formats;
        specs = loongarch_specs;
        render = LoongArchRenderPolicy;
        backend_impl {
            field = LoongArchField;
            register_class = LoongArchRegisterClass;
            architecture_id = ArchitectureId::LoongArch;
            read_instruction = loongarch_read_instruction;
            lookup = loongarch_lookup;
            lower_register = loongarch_lower_register;
            render_policy = loongarch_render_policy;
            apply_aliases = crate::backend::aliases::apply_aliases;
        }
    }
}

impl LoongArchBackend {
    /// Production profile for LA64 (base integer, branch, memory).
    pub fn la64_base() -> DecodeProfile<Self> {
        DecodeProfile {
            mode: LoongArchMode::LA64,
            features: LoongArchFeature::BASE | LoongArchFeature::LA64,
            render_dialect: RenderDialect::Canonical,
            alias_policy: AliasPolicy::None,
        }
    }

    /// Production profile for LA32 (base integer).
    pub fn la32_base() -> DecodeProfile<Self> {
        DecodeProfile {
            mode: LoongArchMode::LA32,
            features: LoongArchFeature::BASE,
            render_dialect: RenderDialect::Canonical,
            alias_policy: AliasPolicy::None,
        }
    }

    /// Test profile with all features and pseudo-instruction aliases enabled.
    pub fn capstone_test_la64() -> DecodeProfile<Self> {
        DecodeProfile {
            mode: LoongArchMode::LA64,
            features: LoongArchFeature::all_supported_for_tests(),
            render_dialect: RenderDialect::Assembler,
            alias_policy: AliasPolicy::PreferPseudo,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoongArchField {
    Rd,
    Rj,
    Rk,
    Ra,
    Cd,
    I8,
    Si12,
    Ui12,
    Si14,
    Si16,
    Si20,
    Si21,
    Ui5,
    Ui6,
    MsbW,
    LsbW,
    MsbD,
    LsbD,
    I26Lo,
    I26Hi,
    Code,
}

robustone_isa_macros::define_registers! {
    arch = LoongArch;
    bank Gpr  { count = 32; base_id = 0;   prefix = "$r"; }
    bank Fpr  { count = 32; base_id = 32;  prefix = "$f"; }
    bank Xr   { count = 32; base_id = 64;  prefix = "$x"; }
    bank Fcc  { count = 8;  base_id = 96; }
    bank Scr  { count = 4;  base_id = 104; }
    bank Fcsr { count = 4;  base_id = 108; }
}

// ============================================================================
// Format specs
// ============================================================================

robustone_isa_macros::define_formats! {
    arch = LoongArch; extern_fields;
    fields { Cd; Code; I26Hi; I26Lo; I8; LsbD; LsbW; MsbD; MsbW; Ra; Rd; Rj; Rk; Si12; Si14; Si16; Si20; Si21; Ui12; Ui5; Ui6; };
    format FMT_R2 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
    };
    format FMT_R3 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        rk: bits(10, 5) as Rk,
    };
    format FMT_R3I2 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        rk: bits(10, 5) as Rk,
        sa2: bits(15, 2) as Ui5,
    };
    format FMT_R3I3 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        rk: bits(10, 5) as Rk,
        ui3: bits(15, 3) as Ui5,
    };
    format FMT_R4 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        rk: bits(10, 5) as Rk,
        ra: bits(15, 5) as Ra,
    };
    format FMT_FCMP {
        cd: bits(0, 3) as Cd,
        fj: bits(5, 5) as Rj,
        fk: bits(10, 5) as Rk,
    };
    format FMT_CSR {
        rd: bits(0, 5) as Rd,
        csr: bits(10, 14) as Si14,
    };
    format FMT_CSRXCHG {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        csr: bits(10, 14) as Si14,
    };
    format FMT_INVTLB {
        imm: bits(0, 5) as Ui5,
        rj: bits(5, 5) as Rj,
        rk: bits(10, 5) as Rk,
    };
    format FMT_R2I8 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        i8: bits(10, 8) as I8,
    };
    format FMT_R2I12 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        si12: bits(10, 12) as Si12,
    };
    format FMT_R2I14 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        si14: bits(10, 14) as Si14,
    };
    format FMT_R2I16 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        si16: bits(10, 16) as Si16,
    };
    format FMT_1RI21 {
        rd: bits(0, 5) as Rd,
        si21: bits(5, 21) as Si21,
    };
    format FMT_I26 {
        i26_lo: bits(0, 16) as I26Lo,
        i26_hi: bits(16, 10) as I26Hi,
    };
    format FMT_R1 {
        rd: bits(0, 5) as Rd,
    };
    format FMT_NONE {};
    format FMT_BJ {
        si16: bits(10, 16) as Si16,
    };
    format FMT_R1I16_BJ {
        rj: bits(5, 5) as Rj,
        si16: bits(10, 16) as Si16,
    };
    format FMT_I15 {
        code: bits(0, 15) as Code,
    };
    format FMT_R2I5 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        ui5: bits(10, 5) as Ui5,
    };
    format FMT_R2I6 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        ui6: bits(10, 6) as Ui6,
    };
    format FMT_R2I3 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        ui3: bits(10, 3) as Ui5,
    };
    format FMT_R2I4 {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        ui4: bits(10, 4) as Ui5,
    };
    format FMT_BSTR_W {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        msb: bits(16, 5) as MsbW,
        lsb: bits(10, 5) as LsbW,
    };
    format FMT_BSTR_D {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        msb: bits(16, 6) as MsbD,
        lsb: bits(10, 6) as LsbD,
    };
    format FMT_1RI20 {
        rd: bits(0, 5) as Rd,
        si20: bits(5, 20) as Si20,
    };
    format FMT_R2I12_U {
        rd: bits(0, 5) as Rd,
        rj: bits(5, 5) as Rj,
        ui12: bits(10, 12) as Ui12,
    };
    format FMT_LDPTE {
        rj: bits(5, 5) as Rj,
        seq: bits(10, 8) as I8,
    }
}

// ============================================================================

include!("backend/specs_integer.rs");
include!("backend/specs_float_arith.rs");
include!("backend/specs_float_cmp.rs");
include!("backend/specs_float_mem.rs");
include!("backend/specs_system.rs");
include!("backend/specs_vector.rs");
// specs_remaining.rs loaded separately — not via include! to avoid spec validation

pub static LOONGARCH_BASE_SPECS: &[InstructionSpec<LoongArchBackend>] = &[
    BSTRINS_W,
    BSTRPICK_W,
    BSTRINS_D,
    BSTRPICK_D,
    ADDU16I_D,
    JIRL,
    B,
    BL,
    BEQZ,
    BNEZ,
    PRELD,
    SLL_W,
    SRL_W,
    SRA_W,
    SLL_D,
    SRL_D,
    SRA_D,
    ROTR_B,
    ROTR_H,
    ROTR_W,
    ROTR_D,
    ADC_B,
    ADC_H,
    ADC_W,
    ADC_D,
    SBC_B,
    SBC_H,
    SBC_W,
    SBC_D,
    RCR_B,
    RCR_H,
    RCR_W,
    RCR_D,
    SLLI_W,
    SLLI_D,
    SRLI_W,
    SRLI_D,
    SRAI_W,
    SRAI_D,
    ROTRI_B,
    ROTRI_H,
    ROTRI_W,
    ROTRI_D,
    RCRI_B,
    RCRI_H,
    RCRI_W,
    RCRI_D,
    ADD_W,
    ADD_D,
    SUB_W,
    SUB_D,
    SLT,
    SLTU,
    MASKEQZ,
    MASKNEZ,
    AND,
    OR,
    XOR,
    NOR,
    ORN,
    ANDN,
    CLO_W,
    CLZ_W,
    CTO_W,
    CTZ_W,
    CLO_D,
    CLZ_D,
    CTO_D,
    CTZ_D,
    REVB_2H,
    REVB_4H,
    REVB_2W,
    REVB_D,
    REVH_2W,
    REVH_D,
    BITREV_4B,
    BITREV_8B,
    BITREV_W,
    BITREV_D,
    EXT_W_H,
    EXT_W_B,
    ASRTLE_D,
    ASRTGT_D,
    ALSL_W,
    ALSL_WU,
    ALSL_D,
    BYTEPICK_W,
    BYTEPICK_D,
    MUL_W,
    MULH_W,
    MULH_WU,
    MUL_D,
    MULH_D,
    MULH_DU,
    MULW_D_W,
    MULW_D_WU,
    DIV_W,
    MOD_W,
    DIV_WU,
    MOD_WU,
    DIV_D,
    MOD_D,
    DIV_DU,
    MOD_DU,
    ADDI_W,
    ADDI_D,
    SLTI,
    SLTUI,
    ANDI,
    ORI,
    XORI,
    ADDU12I_W,
    ADDU12I_D,
    BEQ,
    BNE,
    BLT,
    BGE,
    BLTU,
    BGEU,
    LD_B,
    LD_H,
    LD_W,
    LD_D,
    LD_BU,
    LD_HU,
    LDL_W,
    LDR_W,
    LDL_D,
    LDR_D,
    ST_B,
    ST_H,
    ST_W,
    ST_D,
    STL_W,
    STR_W,
    STL_D,
    STR_D,
    LDX_B,
    LDX_H,
    LDX_W,
    LDX_D,
    STX_B,
    STX_H,
    STX_W,
    STX_D,
    LL_W,
    SC_W,
    LLACQ_W,
    SCREL_W,
    AMSWAP_W,
    AMADD_W,
    AMAND_W,
    AMOR_W,
    AMXOR_W,
    AMMAX_W,
    AMMIN_W,
    DBAR,
    IBAR,
    SYSCALL,
    BREAK,
    DBCL,
    HVCL,
    TLBCLR,
    TLBFLUSH,
    TLBSRCH,
    TLBRD,
    TLBWR,
    TLBFILL,
    ERTN,
    IOCSRRD_B,
    IOCSRRD_H,
    IOCSRRD_W,
    IOCSRRD_D,
    IOCSRWR_B,
    IOCSRWR_H,
    IOCSRWR_W,
    IOCSRWR_D,
    CSRRD,
    CSRWR,
    CSRXCHG,
    GCSRRD,
    GCSRWR,
    GCSRXCHG,
    INVTLB,
    CACOP,
    LDDIR,
    LDPTE,
    GTLBFLUSH,
    IDLE,
    LU12I_W,
    PCADDI,
    PCALAU12I,
    PCADDU12I,
    RDTIMEL_W,
    RDTIMEH_W,
    CPUCFG,
    FFINT_D_L,
    FFINT_D_W,
    FFINT_S_L,
    FFINT_S_W,
    FTINT_L_D,
    FTINT_L_S,
    FTINT_W_D,
    FTINT_W_S,
    FTINTRM_L_D,
    FTINTRM_L_S,
    FTINTRM_W_D,
    FTINTRM_W_S,
    FTINTRNE_L_D,
    FTINTRNE_L_S,
    FTINTRNE_W_D,
    FTINTRNE_W_S,
    FTINTRP_L_D,
    FTINTRP_L_S,
    FTINTRP_W_D,
    FTINTRP_W_S,
    FTINTRZ_L_D,
    FTINTRZ_L_S,
    FTINTRZ_W_D,
    FTINTRZ_W_S,
    FLD_D,
    FLD_S,
    FLDGT_D,
    FLDGT_S,
    FLDLE_D,
    FLDLE_S,
    FLDX_D,
    FLDX_S,
    FMOV_D,
    FMOV_S,
    FST_D,
    FST_S,
    FSTGT_D,
    FSTGT_S,
    FSTLE_D,
    FSTLE_S,
    FSTX_D,
    FSTX_S,
    MOVCF2FR,
    MOVFCSR2GR,
    MOVFR2CF,
    MOVFR2GR_D,
    MOVFR2GR_S,
    MOVGR2FCSR,
    MOVGR2FR_D,
    MOVGR2FR_W,
    FSEL,
    MOVGR2CF,
    MOVCF2GR,
    FABS_D,
    FABS_S,
    FADD_D,
    FADD_S,
    FCLASS_D,
    FCLASS_S,
    FCOPYSIGN_D,
    FCOPYSIGN_S,
    FDIV_D,
    FDIV_S,
    FLOGB_D,
    FLOGB_S,
    FMADD_D,
    FMADD_S,
    FMAX_D,
    FMAX_S,
    FMAXA_D,
    FMAXA_S,
    FMIN_D,
    FMIN_S,
    FMINA_D,
    FMINA_S,
    FMSUB_D,
    FMSUB_S,
    FMUL_D,
    FMUL_S,
    FNEG_D,
    FNEG_S,
    FNMADD_D,
    FNMADD_S,
    FNMSUB_D,
    FNMSUB_S,
    FRECIP_D,
    FRECIP_S,
    FRECIPE_D,
    FRECIPE_S,
    FRINT_D,
    FRINT_S,
    FRSQRT_D,
    FRSQRT_S,
    FRSQRTE_D,
    FRSQRTE_S,
    FSCALEB_D,
    FSCALEB_S,
    FSQRT_D,
    FSQRT_S,
    FSUB_D,
    FSUB_S,
    XVSHUF_B,
    XVSHUF_H,
    XVSHUF_W,
    XVSHUF_D,
    FCMP_CAF_D,
    FCMP_CAF_S,
    FCMP_CEQ_D,
    FCMP_CEQ_S,
    FCMP_CLE_D,
    FCMP_CLE_S,
    FCMP_CLT_D,
    FCMP_CLT_S,
    FCMP_CNE_D,
    FCMP_CNE_S,
    FCMP_COR_D,
    FCMP_COR_S,
    FCMP_CUEQ_D,
    FCMP_CUEQ_S,
    FCMP_CULE_D,
    FCMP_CULE_S,
    FCMP_CULT_D,
    FCMP_CULT_S,
    FCMP_CUN_D,
    FCMP_CUN_S,
    FCMP_CUNE_D,
    FCMP_CUNE_S,
    FCMP_SAF_D,
    FCMP_SAF_S,
    FCMP_SEQ_D,
    FCMP_SEQ_S,
    FCMP_SLE_D,
    FCMP_SLE_S,
    FCMP_SLT_D,
    FCMP_SLT_S,
    FCMP_SNE_D,
    FCMP_SNE_S,
    FCMP_SOR_D,
    FCMP_SOR_S,
    FCMP_SUEQ_D,
    FCMP_SUEQ_S,
    FCMP_SULE_D,
    FCMP_SULE_S,
    FCMP_SULT_D,
    FCMP_SULT_S,
    FCMP_SUN_D,
    FCMP_SUN_S,
    FCMP_SUNE_D,
    FCMP_SUNE_S,
    FCVT_D_LD,
    FCVT_D_S,
    FCVT_LD_D,
    FCVT_S_D,
    FCVT_UD_D,
];

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use robustone_isa::{
        AliasPolicy, ArchitectureBackend, DecodeProfile, RenderDialect, decode_one,
    };

    fn la64_base_profile() -> DecodeProfile<LoongArchBackend> {
        DecodeProfile {
            mode: LoongArchMode::LA64,
            features: LoongArchFeature::BASE | LoongArchFeature::LA64,
            render_dialect: RenderDialect::Canonical,
            alias_policy: AliasPolicy::None,
        }
    }

    #[test]
    fn backend_reads_fixed_4byte_le() {
        let bytes = &[0xAC, 0x39, 0x10, 0x00];
        let result = LoongArchBackend::read_instruction(bytes);
        assert!(result.is_ok());
        let read = result.unwrap();
        assert_eq!(read.raw, 0x0010_39AC);
        assert_eq!(read.length, 4);
    }

    #[test]
    fn backend_decode_add_w() {
        // add.w $t0, $t1, $t2
        // rd=12, rj=13, rk=14
        let word: u32 = 0x0010_0000 | 12 | (13 << 5) | (14 << 10);
        let bytes = word.to_le_bytes();
        let result = decode_one::<LoongArchBackend>(&bytes, 0x1000, &la64_base_profile());
        assert!(result.is_ok(), "{:?}", result);
        let insn = result.unwrap();
        assert_eq!(insn.mnemonic, "add.w");
        assert_eq!(insn.size, 4);
        assert_eq!(insn.registers_written.len(), 1);
        assert_eq!(insn.registers_read.len(), 2);
    }

    #[test]
    fn backend_decode_addi_w() {
        // addi.w $t0, $t1, 42
        // rd=12, rj=13, si12=42
        let word: u32 = 0x0280_0000 | 12 | (13 << 5) | (42 << 10);
        let bytes = word.to_le_bytes();
        let result = decode_one::<LoongArchBackend>(&bytes, 0x1000, &la64_base_profile());
        assert!(result.is_ok(), "{:?}", result);
        let insn = result.unwrap();
        assert_eq!(insn.mnemonic, "addi.w");
        assert_eq!(insn.size, 4);
        assert_eq!(insn.registers_written.len(), 1);
        assert_eq!(insn.registers_read.len(), 1);
        // Immediate operand
        assert_eq!(insn.operands.len(), 3);
        match &insn.operands[2] {
            robustone_core::ir::Operand::Immediate { value, .. } => {
                assert_eq!(*value, 42);
            }
            other => panic!("expected immediate operand, got {:?}", other),
        }
    }

    #[test]
    fn base_specs_have_no_overlaps() {
        assert!(robustone_isa::validate_no_overlaps(LOONGARCH_BASE_SPECS).is_ok());
    }

    #[test]
    fn bl_i26_compose_positive_offset() {
        // BL +0xf8: offs=62, opcode=0x15 at bits 26-31
        let word: u32 = 0x5400_f800;
        let bytes = word.to_le_bytes();
        let result = decode_one::<LoongArchBackend>(&bytes, 0x1000, &la64_base_profile());
        assert!(result.is_ok(), "{:?}", result);
        let insn = result.unwrap();
        assert_eq!(insn.mnemonic, "bl");
        match &insn.operands[0] {
            robustone_core::ir::Operand::Immediate { value, .. } => {
                assert_eq!(*value, 248); // 62 << 2 = 0xf8
            }
            other => panic!("expected immediate operand, got {:?}", other),
        }
    }

    #[test]
    fn bl_i26_compose_match_b_latency() {
        // BL at address 0: encode a forward branch via I26 compose.
        // Verify the decoded immediate is the raw offset (before PC add).
        let bytes: [u8; 4] = [0x00, 0xf8, 0x00, 0x54];
        let result = decode_one::<LoongArchBackend>(&bytes, 0x1000, &la64_base_profile());
        assert!(result.is_ok(), "{:?}", result);
        let insn = result.unwrap();
        assert_eq!(insn.mnemonic, "bl");
        match &insn.operands[0] {
            robustone_core::ir::Operand::Immediate { value, .. } => {
                // offset=62 encoded at bits 10-25, bits 0-9=0 → 62<<2=248=0xf8
                assert_eq!(*value, 248);
            }
            other => panic!("expected immediate operand, got {:?}", other),
        }
    }
}

// ============================================================================
// Aliases (post-decode render hints)
// ============================================================================

mod aliases;

// ============================================================================
// Backend implementation
// ============================================================================

fn loongarch_read_instruction(bytes: &[u8]) -> Result<InstructionRead<u32>, DisasmError> {
    if bytes.len() < 4 {
        return Err(DisasmError::decode_failure(
            robustone_core::types::error::DecodeErrorKind::NeedMoreBytes,
            Some("loongarch".to_string()),
            "need at least 4 bytes",
        ));
    }
    let word = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    Ok(InstructionRead {
        raw: word,
        length: 4,
    })
}

fn loongarch_lookup(
    word: u32,
    profile: &DecodeProfile<LoongArchBackend>,
) -> Option<&'static InstructionSpec<LoongArchBackend>> {
    let tables: &[&[InstructionSpec<LoongArchBackend>]] = &[LOONGARCH_BASE_SPECS, VECTOR_SPECS];
    tables
        .iter()
        .flat_map(|t| t.iter())
        .find(|spec| {
            (word & spec.pattern().mask) == spec.pattern().value
                && spec.modes().matches(profile.mode)
                && profile.features.contains(spec.features())
        })
}

fn loongarch_lower_register(
    class: LoongArchRegisterClass,
    raw: u32,
    _profile: &DecodeProfile<LoongArchBackend>,
) -> RegisterId {
    match lower_register(class, raw) {
        Ok(id) => RegisterId::loongarch(id),
        Err(_) => RegisterId::loongarch(raw),
    }
}

fn loongarch_render_policy(
    profile: &DecodeProfile<LoongArchBackend>,
) -> RenderPolicy<LoongArchBackend> {
    RenderPolicy::new(profile.render_dialect, profile.alias_policy)
}

