#![forbid(unsafe_code)]

//! Minimal ARM backend using the shared ISA framework.
//!
//! Mode, feature, and backend types are generated by `define_arch!`.
//! The `ArchitectureBackend` trait impl is also generated by the macro
//! via `backend_impl { ... }`, delegating to standalone functions below.

use robustone_core::ir::{ArchitectureId, RegisterId};
use robustone_core::types::error::{DecodeErrorKind, DisasmError};
use robustone_isa::{
    DecodeProfile, FormatSpec, InstructionRead, InstructionSpec, ModeSet, RenderPolicy,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArmField {
    Rd,
    Rn,
    Imm12,
    Imm16,
}

robustone_isa_macros::define_registers! {
    arch = Arm;
    bank Gpr {
        count = 31;
        base_id = 0;
        canonical = "x{n}";
    }
}

robustone_isa_macros::define_arch! {
    pub arch Arm {
        word = u32;
        endian = little;
        instruction_length = fixed(4);
        modes { AArch64 = "aarch64"; };
        features: u8 { BASE = 0; };
        registers = arm_registers;
        formats = arm_formats;
        specs = arm_specs;
        render = ArmRenderPolicy;
        backend_impl {
            field = ArmField;
            register_class = ArmRegisterClass;
            architecture_id = ArchitectureId::Arm;
            read_instruction = arm_read_instruction;
            lookup = arm_lookup;
            lower_register = arm_lower_register;
            render_policy = arm_render_policy;
            extract_field = arm_extract_field;
        }
    }
}

fn arm_read_instruction(bytes: &[u8]) -> Result<InstructionRead<u32>, DisasmError> {
    if bytes.len() < 4 {
        return Err(DisasmError::decode_failure(
            DecodeErrorKind::NeedMoreBytes,
            Some("arm".to_string()),
            "need 4 bytes",
        ));
    }
    let word = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    Ok(InstructionRead {
        raw: word,
        length: 4,
    })
}

fn arm_lookup(
    word: u32,
    _profile: &DecodeProfile<ArmBackend>,
) -> Option<&'static InstructionSpec<ArmBackend>> {
    SPECS
        .iter()
        .find(|spec| (word & spec.pattern().mask) == spec.pattern().value)
}

fn arm_lower_register(
    _class: ArmRegisterClass,
    raw: u32,
    _profile: &DecodeProfile<ArmBackend>,
) -> RegisterId {
    RegisterId::arm(raw)
}

fn arm_render_policy(_profile: &DecodeProfile<ArmBackend>) -> RenderPolicy<ArmBackend> {
    RenderPolicy::new(
        robustone_isa::RenderDialect::Canonical,
        robustone_isa::AliasPolicy::None,
    )
}

fn arm_extract_field(
    word: u32,
    format: &FormatSpec<ArmField>,
    field: ArmField,
) -> Result<u32, DisasmError> {
    for f in format.fields() {
        if f.field_type() == field {
            let mask = ((1u64 << f.length()) - 1) as u32;
            return Ok((word >> f.start()) & mask);
        }
    }
    Err(DisasmError::decode_failure(
        DecodeErrorKind::InternalSpecBug,
        Some("aarch64".to_string()),
        format!("field {:?} not found in format {}", field, format.name()),
    ))
}

robustone_isa_macros::define_formats! {
    arch = Arm; extern_fields;
    fields { Rd; Rn; Imm12; Imm16; };
    format R {
        Rd: bits(0, 5) as Rd,
    };
    format I_ADD {
        Rd: bits(0, 5) as Rd,
        Rn: bits(5, 5) as Rn,
        Imm12: bits(10, 12) as Imm12,
    };
    format I_MOVZ {
        Rd: bits(0, 5) as Rd,
        Imm16: bits(5, 16) as Imm16,
    }
}

robustone_isa_macros::define_instructions! {
    arch = Arm; module = base;
    insn NOP {
        mnemonic = "nop";
        opcode_id = "NOP";
        pattern = robustone_isa::mask_value!(0xFFFF_FFFF, 0xD5_03_20_1F);
        format = &R;
        operands = &[];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::System];
        effect = None;
        manual = "ARM ARM";
    }
    insn RET {
        mnemonic = "ret";
        opcode_id = "RET";
        pattern = robustone_isa::mask_value!(0xFFFF_FFFF, 0xD6_5F_03_C0);
        format = &R;
        operands = &[];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Jump];
        effect = Return;
        manual = "ARM ARM";
    }
    insn ADD_IMM {
        mnemonic = "add";
        opcode_id = "ADD_IMM";
        pattern = robustone_isa::mask_value!(0xFF00_0000, 0x9100_0000);
        format = &I_ADD;
        operands = &[
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rd, robustone_isa::Access::Write),
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rn, robustone_isa::Access::Read),
            robustone_isa::imm!(ArmField::Imm12, robustone_isa::ImmediateTransform::None, robustone_isa::ImmediateKind::Unsigned),
        ];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Arithmetic];
        manual = "ARM ARM";
    }
    insn MOVZ {
        mnemonic = "mov";
        opcode_id = "MOVZ";
        pattern = robustone_isa::mask_value!(0xFFE0_0000, 0xD280_0000);
        format = &I_MOVZ;
        operands = &[
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rd, robustone_isa::Access::Write),
            robustone_isa::imm!(ArmField::Imm16, robustone_isa::ImmediateTransform::None, robustone_isa::ImmediateKind::Unsigned),
        ];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Arithmetic];
        manual = "ARM ARM";
    }
}
