loongarch_insn!(
    FFINT_D_L,
    "ffint.d.l",
    "FFINT_D_L",
    0xFFFFFC00,
    0x011D2800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FFINT_D_W,
    "ffint.d.w",
    "FFINT_D_W",
    0xFFFFFC00,
    0x011D2000,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FFINT_S_L,
    "ffint.s.l",
    "FFINT_S_L",
    0xFFFFFC00,
    0x011D1800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FFINT_S_W,
    "ffint.s.w",
    "FFINT_S_W",
    0xFFFFFC00,
    0x011D1000,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINT_L_D,
    "ftint.l.d",
    "FTINT_L_D",
    0xFFFFFC00,
    0x011B2800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINT_L_S,
    "ftint.l.s",
    "FTINT_L_S",
    0xFFFFFC00,
    0x011B2400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINT_W_D,
    "ftint.w.d",
    "FTINT_W_D",
    0xFFFFFC00,
    0x011B0800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINT_W_S,
    "ftint.w.s",
    "FTINT_W_S",
    0xFFFFFC00,
    0x011B0400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRM_L_D,
    "ftintrm.l.d",
    "FTINTRM_L_D",
    0xFFFFFC00,
    0x011A2800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRM_L_S,
    "ftintrm.l.s",
    "FTINTRM_L_S",
    0xFFFFFC00,
    0x011A2400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRM_W_D,
    "ftintrm.w.d",
    "FTINTRM_W_D",
    0xFFFFFC00,
    0x011A0800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRM_W_S,
    "ftintrm.w.s",
    "FTINTRM_W_S",
    0xFFFFFC00,
    0x011A0400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRNE_L_D,
    "ftintrne.l.d",
    "FTINTRNE_L_D",
    0xFFFFFC00,
    0x011AE800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRNE_L_S,
    "ftintrne.l.s",
    "FTINTRNE_L_S",
    0xFFFFFC00,
    0x011AE400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRNE_W_D,
    "ftintrne.w.d",
    "FTINTRNE_W_D",
    0xFFFFFC00,
    0x011AC800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRNE_W_S,
    "ftintrne.w.s",
    "FTINTRNE_W_S",
    0xFFFFFC00,
    0x011AC400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRP_L_D,
    "ftintrp.l.d",
    "FTINTRP_L_D",
    0xFFFFFC00,
    0x011A6800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRP_L_S,
    "ftintrp.l.s",
    "FTINTRP_L_S",
    0xFFFFFC00,
    0x011A6400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRP_W_D,
    "ftintrp.w.d",
    "FTINTRP_W_D",
    0xFFFFFC00,
    0x011A4800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRP_W_S,
    "ftintrp.w.s",
    "FTINTRP_W_S",
    0xFFFFFC00,
    0x011A4400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRZ_L_D,
    "ftintrz.l.d",
    "FTINTRZ_L_D",
    0xFFFFFC00,
    0x011AA800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRZ_L_S,
    "ftintrz.l.s",
    "FTINTRZ_L_S",
    0xFFFFFC00,
    0x011AA400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRZ_W_D,
    "ftintrz.w.d",
    "FTINTRZ_W_D",
    0xFFFFFC00,
    0x011A8800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FTINTRZ_W_S,
    "ftintrz.w.s",
    "FTINTRZ_W_S",
    0xFFFFFC00,
    0x011A8400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FLD_D,
    "fld.d",
    "FLD_D",
    0xFFC00000,
    0x2B800000,
    &FMT_R2I12,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::imm!(
            LoongArchField::Si12,
            ImmediateTransform::SignExtend { bits: 12 },
            ImmediateKind::Absolute
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLD_S,
    "fld.s",
    "FLD_S",
    0xFFC00000,
    0x2B000000,
    &FMT_R2I12,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::imm!(
            LoongArchField::Si12,
            ImmediateTransform::SignExtend { bits: 12 },
            ImmediateKind::Absolute
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDGT_D,
    "fldgt.d",
    "FLDGT_D",
    0xFFFF8000,
    0x38748000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDGT_S,
    "fldgt.s",
    "FLDGT_S",
    0xFFFF8000,
    0x38740000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDLE_D,
    "fldle.d",
    "FLDLE_D",
    0xFFFF8000,
    0x38758000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDLE_S,
    "fldle.s",
    "FLDLE_S",
    0xFFFF8000,
    0x38750000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDX_D,
    "fldx.d",
    "FLDX_D",
    0xFFFF8000,
    0x38340000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FLDX_S,
    "fldx.s",
    "FLDX_S",
    0xFFFF8000,
    0x38300000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FMOV_D,
    "fmov.d",
    "FMOV_D",
    0xFFFFFC00,
    0x01149800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FMOV_S,
    "fmov.s",
    "FMOV_S",
    0xFFFFFC00,
    0x01149400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    FST_D,
    "fst.d",
    "FST_D",
    0xFFC00000,
    0x2BC00000,
    &FMT_R2I12,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::imm!(
            LoongArchField::Si12,
            ImmediateTransform::SignExtend { bits: 12 },
            ImmediateKind::Absolute
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FST_S,
    "fst.s",
    "FST_S",
    0xFFC00000,
    0x2B400000,
    &FMT_R2I12,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::imm!(
            LoongArchField::Si12,
            ImmediateTransform::SignExtend { bits: 12 },
            ImmediateKind::Absolute
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTGT_D,
    "fstgt.d",
    "FSTGT_D",
    0xFFFF8000,
    0x38768000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTGT_S,
    "fstgt.s",
    "FSTGT_S",
    0xFFFF8000,
    0x38760000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTLE_D,
    "fstle.d",
    "FSTLE_D",
    0xFFFF8000,
    0x38778000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTLE_S,
    "fstle.s",
    "FSTLE_S",
    0xFFFF8000,
    0x38770000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTX_D,
    "fstx.d",
    "FSTX_D",
    0xFFFF8000,
    0x383C0000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    FSTX_S,
    "fstx.s",
    "FSTX_S",
    0xFFFF8000,
    0x38380000,
    &FMT_R3,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rk,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Memory]
);

loongarch_insn!(
    MOVCF2FR,
    "movcf2fr",
    "MOVCF2FR",
    0xFFFFFC00,
    0x0114D400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fcc,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVFCSR2GR,
    "movfcsr2gr",
    "MOVFCSR2GR",
    0xFFFFFC00,
    0x0114C800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fcsr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVFR2CF,
    "movfr2cf",
    "MOVFR2CF",
    0xFFFFFC00,
    0x0114D000,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fcc,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVFR2GR_D,
    "movfr2gr.d",
    "MOVFR2GR_D",
    0xFFFFFC00,
    0x0114B800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVFR2GR_S,
    "movfr2gr.s",
    "MOVFR2GR_S",
    0xFFFFFC00,
    0x0114B400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVGR2FCSR,
    "movgr2fcsr",
    "MOVGR2FCSR",
    0xFFFFFC00,
    0x0114C000,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fcsr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVGR2FR_D,
    "movgr2fr.d",
    "MOVGR2FR_D",
    0xFFFFFC00,
    0x0114A800,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);

loongarch_insn!(
    MOVGR2FR_W,
    "movgr2fr.w",
    "MOVGR2FR_W",
    0xFFFFFC00,
    0x0114A400,
    &FMT_R2,
    &[
        robustone_isa::reg!(
            LoongArchRegisterClass::Fpr,
            LoongArchField::Rd,
            Access::Write
        ),
        robustone_isa::reg!(
            LoongArchRegisterClass::Gpr,
            LoongArchField::Rj,
            Access::Read
        ),
    ],
    &[InstructionGroup::Float, InstructionGroup::Arithmetic]
);



loongarch_insn!(
    FSEL,
    "fsel",
    "FSEL",
    0xFFFC_0000,
    0x0D00_0000,
    &FMT_R4,
    &[
        robustone_isa::reg!(LoongArchRegisterClass::Fpr, LoongArchField::Rd, Access::Write),
        robustone_isa::reg!(LoongArchRegisterClass::Fpr, LoongArchField::Rj, Access::Read),
        robustone_isa::reg!(LoongArchRegisterClass::Fpr, LoongArchField::Rk, Access::Read),
        robustone_isa::reg!(LoongArchRegisterClass::Fcc, LoongArchField::Ra, Access::Read),
    ],
    &[InstructionGroup::Float, InstructionGroup::Float]
);

loongarch_insn!(
    MOVGR2CF,
    "movgr2cf",
    "MOVGR2CF",
    0xFFFF_FC00,
    0x0114_D800,
    &FMT_R2,
    &[
        robustone_isa::reg!(LoongArchRegisterClass::Fcc, LoongArchField::Rd, Access::Write),
        robustone_isa::reg!(LoongArchRegisterClass::Gpr, LoongArchField::Rj, Access::Read),
    ],
    &[InstructionGroup::Float, InstructionGroup::Float]
);

loongarch_insn!(
    MOVCF2GR,
    "movcf2gr",
    "MOVCF2GR",
    0xFFFF_FC00,
    0x0114_DC00,
    &FMT_R2,
    &[
        robustone_isa::reg!(LoongArchRegisterClass::Gpr, LoongArchField::Rd, Access::Write),
        robustone_isa::reg!(LoongArchRegisterClass::Fcc, LoongArchField::Rj, Access::Read),
    ],
    &[InstructionGroup::Float, InstructionGroup::Float]
);
