#![forbid(unsafe_code)]

//! ARM (AArch64) backend using the shared ISA framework.
//!
//! Mode, feature, and backend types are generated by `define_arch!`.
//! The `ArchitectureBackend` trait impl is also generated by the macro
//! via `backend_impl { ... }`, delegating to standalone functions below.

use robustone_core::ir::{ArchitectureId, RegisterId};
use robustone_core::types::error::{DecodeErrorKind, DisasmError};
use robustone_isa::{DecodeProfile, FeatureSet, FormatSpec, InstructionRead, InstructionSpec, ModeSet};

// ---------------------------------------------------------------------------
// Field enum
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArmField {
    // General-purpose registers
    Rd, Rn, Rm, Ra, Rt, Rt2, Rs,
    // Immediates
    Imm12, Imm16, Imm19, Imm26,
    Immhi, Immlo, Imm7,
    Cond,
    Shift, Imm6, Hw,
    N, Immr, Imms,
    // FP / SIMD
    Ftype, Opcode, Size, Q, U, L, M, H,
}

// ---------------------------------------------------------------------------
// Registers
// ---------------------------------------------------------------------------

robustone_isa_macros::define_registers! {
    arch = Arm;
    bank Gpr {
        count = 31;
        base_id = 0;
        canonical = "x{n}";
    }
    bank Vec {
        count = 32;
        base_id = 64;
        canonical = "v{n}";
    }
}

// ---------------------------------------------------------------------------
// Architecture definition
// ---------------------------------------------------------------------------

robustone_isa_macros::define_arch! {
    pub arch Arm {
        word = u32;
        endian = little;
        instruction_length = fixed(4);
        modes { AArch64 = "aarch64"; };
        features: u8 { BASE = 0; FP = 1; SIMD = 2; CRYPTO = 3; };
        registers = arm_registers;
        formats = arm_formats;
        specs = arm_specs;
        render = ArmRenderPolicy;
        backend_impl {
            field = ArmField;
            register_class = ArmRegisterClass;
            architecture_id = ArchitectureId::Arm;
            read_instruction = arm_read_instruction;
            lookup = arm_lookup;
            lower_register = arm_lower_register;
            extract_field = arm_extract_field;
        }
    }
}

// ---------------------------------------------------------------------------
// Backend functions
// ---------------------------------------------------------------------------

fn arm_read_instruction(bytes: &[u8]) -> Result<InstructionRead<u32>, DisasmError> {
    if bytes.len() < 4 {
        return Err(DisasmError::decode_failure(
            DecodeErrorKind::NeedMoreBytes,
            Some("arm".to_string()),
            "need 4 bytes",
        ));
    }
    let word = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    Ok(InstructionRead {
        raw: word,
        length: 4,
    })
}

fn arm_lookup(
    word: u32,
    profile: &DecodeProfile<ArmBackend>,
) -> Option<&'static InstructionSpec<ArmBackend>> {
    let op0 = ((word >> 25) & 0xF) as u8;

    // Hierarchical dispatch: pre-filter by op0 range before linear match.
    SPECS.iter().find(|spec| {
        // Quick reject: check if spec's pattern value aligns with op0
        let spec_op0 = ((spec.pattern().value >> 25) & 0xF) as u8;
        let spec_mask = ((spec.pattern().mask >> 25) & 0xF) as u8;
        let op0_matches = (op0 & spec_mask) == spec_op0;

        op0_matches
            && (word & spec.pattern().mask) == spec.pattern().value
            && profile.features.contains(spec.features())
    })
}

fn arm_lower_register(
    class: ArmRegisterClass,
    raw: u32,
    _profile: &DecodeProfile<ArmBackend>,
) -> RegisterId {
    match lower_register(class, raw) {
        Ok(id) => RegisterId::arm(id),
        Err(_) => RegisterId::arm(raw),
    }
}

fn arm_extract_field(
    word: u32,
    format: &FormatSpec<ArmField>,
    field: ArmField,
) -> Result<u32, DisasmError> {
    // Search format fields for matching field type and extract bits
    for f in format.fields() {
        if f.field_type() == field {
            let mask = ((1u64 << f.length()) - 1) as u32;
            return Ok((word >> f.start()) & mask);
        }
    }
    Err(DisasmError::decode_failure(
        DecodeErrorKind::InvalidField,
        Some("arm".to_string()),
        format!("field {:?} not found in format {}", field, format.name()),
    ))
}

// ---------------------------------------------------------------------------
// Formats
// ---------------------------------------------------------------------------

robustone_isa_macros::define_formats! {
    arch = Arm;
    extern_fields;
    fields { Rd; Rn; Rm; Ra; Rt; Rt2; Imm12; Imm16; Imm19; Imm26; Immhi; Immlo; Imm7; Cond; Shift; Imm6; Hw; N; Immr; Imms; Ftype; Opcode; Size; Q; U; L; M; H; };

    format R_TYPE {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
    };
    format R_4REG {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
        ra: bits(10, 5) as Ra,
    };
    format R_COND {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
        cond: bits(12, 4) as Cond,
    };
    format I_ADD {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        imm12: bits(10, 12) as Imm12,
        shift: bits(22, 1) as Shift,
    };
    format I_MOVZ {
        rd: bits(0, 5) as Rd,
        imm16: bits(5, 16) as Imm16,
        hw: bits(21, 2) as Hw,
    };
    format B_UNCOND {
        imm26: bits(0, 26) as Imm26,
    };
    format B_COND {
        imm19: bits(5, 19) as Imm19,
        cond: bits(0, 4) as Cond,
    };
    format CBZ {
        rt: bits(0, 5) as Rt,
        imm19: bits(5, 19) as Imm19,
    };
    format TBZ {
        rt: bits(0, 5) as Rt,
        imm14: bits(5, 14) as Imm19,
        b5: bits(19, 1) as Q,
        b40: bits(24, 5) as Imm6,
    };
    format ADR {
        rd: bits(0, 5) as Rd,
        immhi: bits(5, 19) as Immhi,
        immlo: bits(29, 2) as Immlo,
    };
    format EXCEPT {
        imm16: bits(5, 16) as Imm16,
    };
    format BARRIER {
        crm: bits(8, 4) as Imm6,
    };
    format LDR_IMM {
        rt: bits(0, 5) as Rt,
        rn: bits(5, 5) as Rn,
        imm12: bits(10, 12) as Imm12,
    };
    format LDR_REG {
        rt: bits(0, 5) as Rt,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
        option: bits(13, 3) as Opcode,
        s: bits(12, 1) as Shift,
    };
    format LDP {
        rt: bits(0, 5) as Rt,
        rt2: bits(10, 5) as Rt2,
        rn: bits(5, 5) as Rn,
        imm7: bits(15, 7) as Imm7,
    };
    format FP_1SOURCE {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        ftype: bits(22, 2) as Ftype,
    };
    format FP_2SOURCE {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
        ftype: bits(22, 2) as Ftype,
    };
    format VEC_THREE_SAME {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        rm: bits(16, 5) as Rm,
        size: bits(22, 2) as Size,
        q: bits(30, 1) as Q,
    };
    format VEC_TWO_REG {
        rd: bits(0, 5) as Rd,
        rn: bits(5, 5) as Rn,
        size: bits(22, 2) as Size,
        q: bits(30, 1) as Q,
    };
}

// ---------------------------------------------------------------------------
// Instructions
// ---------------------------------------------------------------------------

robustone_isa_macros::define_instructions! {
    arch = Arm; module = base;

    insn NOP {
        mnemonic = "nop";
        opcode_id = "NOP";
        pattern = robustone_isa::mask_value!(0xFFFF_FFFF, 0xD5_03_20_1F);
        format = &R_TYPE;
        operands = &[];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::System];
        effect = None;
        manual = "ARM ARM";
    }
    insn RET {
        mnemonic = "ret";
        opcode_id = "RET";
        pattern = robustone_isa::mask_value!(0xFFFF_FFFF, 0xD6_5F_03_C0);
        format = &R_TYPE;
        operands = &[];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Jump];
        effect = Return;
        manual = "ARM ARM";
    }
    insn ADD_IMM {
        mnemonic = "add";
        opcode_id = "ADD_IMM";
        pattern = robustone_isa::mask_value!(0xFF00_0000, 0x9100_0000);
        format = &I_ADD;
        operands = &[
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rd, robustone_isa::Access::Write),
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rn, robustone_isa::Access::Read),
            robustone_isa::imm!(ArmField::Imm12, robustone_isa::ImmediateTransform::None, robustone_isa::ImmediateKind::Unsigned),
        ];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Arithmetic];
        manual = "ARM ARM";
    }
    insn MOVZ {
        mnemonic = "movz";
        opcode_id = "MOVZ";
        pattern = robustone_isa::mask_value!(0xFFE0_0000, 0xD280_0000);
        format = &I_MOVZ;
        operands = &[
            robustone_isa::reg!(ArmRegisterClass::Gpr, ArmField::Rd, robustone_isa::Access::Write),
            robustone_isa::imm!(ArmField::Imm16, robustone_isa::ImmediateTransform::None, robustone_isa::ImmediateKind::Unsigned),
        ];
        modes = ModeSet::All;
        features = ArmFeature::BASE;
        groups = &[robustone_isa::InstructionGroup::Arithmetic];
        manual = "ARM ARM";
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use robustone_isa::Decoder;

    fn make_profile() -> DecodeProfile<ArmBackend> {
        DecodeProfile {
            mode: ArmMode::AArch64,
            features: ArmFeature::all(),
            render_dialect: robustone_isa::RenderDialect::Canonical,
            alias_policy: robustone_isa::AliasPolicy::None,
        }
    }

    #[test]
    fn test_decode_nop() {
        let decoder = Decoder::<ArmBackend>::new();
        let profile = make_profile();
        let insn = decoder.decode(&[0x1F, 0x20, 0x03, 0xD5], 0, &profile).unwrap();
        assert_eq!(insn.mnemonic, "nop");
    }

    #[test]
    fn test_decode_ret() {
        let decoder = Decoder::<ArmBackend>::new();
        let profile = make_profile();
        let insn = decoder.decode(&[0xC0, 0x03, 0x5F, 0xD6], 0, &profile).unwrap();
        assert_eq!(insn.mnemonic, "ret");
    }
}
