[package]
name = "robustone"
version = "0.0.0"
edition = "2024"

[dependencies]
robustone-core = { path = "../robustone-core", default-features = false }
robustone-cli = { path = "../robustone-cli" }

[features]
default = ["riscv"]
riscv = ["robustone-core/riscv"]
