#![forbid(unsafe_code)]

//! Minimal x86 backend using the shared ISA framework.
//!
//! Mode, feature, and backend types are generated by `define_arch!`.

use robustone_core::ir::{ArchitectureId, RegisterId};
use robustone_core::types::error::{DecodeErrorKind, DisasmError};
use robustone_isa::{
    DecodeProfile, FormatSpec, InstructionRead, InstructionSpec, ModeSet, RenderPolicy,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum X86Field {
    Modrm,
}

robustone_isa_macros::define_registers! {
    arch = X86;
    bank Gpr {
        count = 16;
        base_id = 0;
        prefix = "r";
    }
}

robustone_isa_macros::define_arch! {
    pub arch X86 {
        word = u32;
        endian = little;
        instruction_length = variable(15);
        modes { X64 = "x64"; };
        features: u8 { BASE = 0; };
        registers = x86_registers;
        formats = x86_formats;
        specs = x86_specs;
        render = X86RenderPolicy;
        backend_impl {
            field = X86Field;
            register_class = X86RegisterClass;
            architecture_id = ArchitectureId::X86;
            read_instruction = x86_read_instruction;
            lookup = x86_lookup;
            lower_register = x86_lower_register;
            render_policy = x86_render_policy;
            extract_field = x86_extract_field;
        }
    }
}

fn x86_read_instruction(bytes: &[u8]) -> Result<InstructionRead<u32>, DisasmError> {
    if bytes.is_empty() {
        return Err(DisasmError::decode_failure(
            DecodeErrorKind::NeedMoreBytes,
            Some("x86".to_string()),
            "need at least 1 byte",
        ));
    }
    let word = bytes[0] as u32;
    Ok(InstructionRead {
        raw: word,
        length: 1,
    })
}

fn x86_lookup(
    word: u32,
    _profile: &DecodeProfile<X86Backend>,
) -> Option<&'static InstructionSpec<X86Backend>> {
    SPECS
        .iter()
        .find(|spec| (word & spec.pattern().mask) == spec.pattern().value)
}

fn x86_lower_register(
    class: X86RegisterClass,
    raw: u32,
    _profile: &DecodeProfile<X86Backend>,
) -> RegisterId {
    match lower_register(class, raw) {
        Ok(id) => RegisterId::x86(id),
        Err(_) => RegisterId::x86(raw),
    }
}

fn x86_render_policy(_profile: &DecodeProfile<X86Backend>) -> RenderPolicy<X86Backend> {
    RenderPolicy::new(
        robustone_isa::RenderDialect::Canonical,
        robustone_isa::AliasPolicy::None,
    )
}

fn x86_extract_field(
    word: u32,
    format: &FormatSpec<X86Field>,
    field: X86Field,
) -> Result<u32, DisasmError> {
    for f in format.fields() {
        if f.field_type() == field {
            let mask = ((1u64 << f.length()) - 1) as u32;
            return Ok((word >> f.start()) & mask);
        }
    }
    Err(DisasmError::decode_failure(
        DecodeErrorKind::InternalSpecBug,
        Some("x86".to_string()),
        format!("field {:?} not found in format {}", field, format.name()),
    ))
}

robustone_isa_macros::define_formats! {
    arch = X86; extern_fields;
    fields { Modrm; };
    format R { Modrm: bits(0, 8) }
}

robustone_isa_macros::define_instructions! {
    arch = X86; module = base;
    insn NOP {
        mnemonic = "nop";
        opcode_id = "NOP";
        pattern = robustone_isa::mask_value!(0xFFFF_FFFF, 0x0000_0090);
        format = &R;
        operands = &[];
        modes = ModeSet::All;
        features = X86Feature::BASE;
        groups = &[robustone_isa::InstructionGroup::System];
        effect = None;
        manual = "Intel SDM";
    }
}
